config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "contacts#index"

  resources :contacts
  resources :messages do
    collection do
      get :list
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  belongs_to :member, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  after_create_commit {
    MessageBroadcastJob.perform_later self
    PushBroadcastJob.perform_later self
  }

  class << self
    def room_num(id1, id2)
      [id1, id2].map(&:to_i).sort.join('_')
    end

    def unread_count(sender_id, receiver_id)
      Message.where("receiver_id=? and sender_id=? and read_at is null", receiver_id, sender_id).count
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :sent_messages, as: :sender
  has_many :received_messages, as: :receiver
  has_many :contacts, foreign_key: 'owner_id'

  def label_name
    email
  end

  def add_contact(member)
    contact = self.contacts.where(member_id: member.id).first
    if contact.nil?
      contact = self.contacts.build member_id: member.id
      contact.save!
    end
    contact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :authenticate_user!, :set_user_cookies
  helper_method :set_user_cookies

  before_action do
    if devise_controller?
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation) }
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    end
  end

  private
  def set_user_cookies
    cookies.signed[:user_id] = current_user.id if current_user
  end
end

app/controllers/contacts_controller.rb
# -*- coding: utf-8 -*-
class ContactsController < ApplicationController
  def index
    @contacts = Contact.where("owner_id=?", current_user.id).order("last_call_time desc").limit(20)
  end

  def new
    @contact = Contact.new
  end

  def create
    user = User.find_by_email params[:email]
    if user.nil?
      flash[:notice] = "用户不存在"
      render :new
      return
    end

    @contact = current_user.add_contact(user)

    # [todo] 需要对方同意才能加为联系人
    user.add_contact(current_user)

    redirect_to list_messages_path(friend_id: @contact.member_id)
  end

  def destroy
    @contact = Contact.find params[:id]
    @contact.destroy
    redirect_to contacts_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def list
    @friend = User.find params[:friend_id]
    field_values = [params[:friend_id], current_user.id]*2
    # find messages by sender and receiver, and order by created_at
    @messages = Message.where('(sender_id=? and receiver_id=?) or (receiver_id=? and sender_id=?)', *field_values).order("created_at desc").limit(20)

    unread_ids = @messages.collect {|msg|
      msg.id if msg.read_at.nil? && msg.receiver_id == current_user.id
    }.compact

    Message.where(id: unread_ids, receiver_id: current_user.id).update_all(read_at: Time.now)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time(t)
    t.strftime("%Y-%m-%d %H:%M")
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def unread_tag(sender_id, receiver_id)
    cnt = Message.unread_count(sender_id, receiver_id)
    unread_class = (cnt > 0 ? 'unread' : '')
    content_tag(:span, cnt, class: "badge #{unread_class}")
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.haml
.list-group-item(id="member-#{contact.member_id}")
  = link_to list_messages_path(friend_id: contact.member_id), class: "", "data-turbolinks" => false do
    = unread_tag(contact.member_id, current_user.id)
    = contact.member.label_name

  %button.close(aria-label="Close")
    = link_to contact_path(contact), method: :delete, data:{ confirm: "确认删除联系人？" } do
      %span(aria-hidden="true") &times;

app/views/contacts/index.html.haml
%h3.page-header 联系人列表

#contacts.list-group
  = render @contacts

app/views/contacts/new.html.haml
%h3.page-header 添加联系人

= form_tag contacts_path, method: :post do
  .row
    .col-xs-9
      .input-group.input-group
        %span#sizing-addon.input-group-addon @
        = text_field_tag :email, "", class: "form-control", placeholder: "Email", "aria-describedby" => "sizing-addon"

    .col-xs-3
      = submit_tag "添加", class: "btn btn-primary"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tags
    %title 聊天室
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render partial: '/shared/header'

    .container
      - if notice
        %pre.notice= notice
      - if alert
        %pre.alert= alert
      = yield

app/views/messages/_message.html.haml
%div.clearfix
  - if message.sender === current_user
    .popover.left
      .arrow
      %h3.popover-title
        %div= "#{message.sender.label_name}："
        %small= format_time(message.created_at)
      .popover-content
        %p= message.content
  - else
    .popover.right
      .arrow
      %h3.popover-title
        %div= "#{message.sender.label_name}："
        %small= format_time(message.created_at)
      .popover-content
        %p= message.content

app/views/messages/list.html.haml
%h3.page-header= "与 #{@friend.label_name} 的谈话"
#message-list
  = render @messages.reverse

= hidden_field_tag "friend_id", params[:friend_id], id: "friend-id"

.navbar.navbar-fixed-bottom
  .container
    .row
      .col-xs-9
        = text_field_tag "content", "", class: "form-control", id: "msg-content"
      .col-xs-3
        = submit_tag "发送", class: "btn btn-primary send-message"

app/views/shared/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "聊天室", "/", class: "navbar-brand"

    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to "联系人", contacts_path, 'data-turbolinks' => false
        %li
          = link_to "添加联系人", new_contact_path
        %li
          - if current_user
            = link_to "退出", destroy_user_session_path, method: :delete
          - else
            = link_to "登录", user_session_path